In [31]:
import numpy as np
import pandas as pd
from bokeh.io import output_file, output_notebook, curdoc
from bokeh.layouts import row, gridplot
from bokeh.plotting import figure, show, reset_output
from bokeh.models import HoverTool, Label, WheelZoomTool, PanTool, Span
output_notebook()

Loading BokehJS ...

## Linear regression fit classification

In [32]:
# df = pd.read_csv("df2.csv", sep=" ", header = None)

df = pd.read_csv("df2.csv", header = None).T
x = np.array(df[[0]])
y = np.array(df[[1]])

ones = np.ones(x.size)
X = np.column_stack((ones, x))
w = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, y))
y_hat = w[0] + w[1] * x
x = x.flatten()
y = y.flatten()
y_hat = y_hat.flatten()

In [33]:
## Plot

output_file("logit_00.html")
p1 = figure(plot_height = 300, plot_width = 300,
            tools = "")
p2 = figure(plot_height = 300, plot_width = 300,
            tools = "", title = "Linear Regression")
p1.circle(x = x, y = y)
p2.circle(x = x, y = y)
p2.line(x = x, y = y_hat, color = 'red')
hline = Span(location=0.5,  dimension='width', line_color='green', 
             line_dash='dashed', line_width=3)
p1.add_layout(hline)
p2.add_layout(hline)
p1.toolbar.logo = None
p2.toolbar.logo = None
show(row(p1, p2))

## Logistic Sigmoid

In [34]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(solver='lbfgs')
clf.fit(X, y)
y_new = clf.predict(X)


output_file("logit_01.html")
p3 = figure(plot_height = 300, plot_width = 300,
            tools = "", title = "scikit-learn")
p3.circle(x = x, y = y)
p3.toolbar.logo = None
p3.add_layout(hline)
p3.line(x = x, y = y_new, color = "red")
show(row(p2, p3))

## Least Squares Cost Function

In [5]:
def sigmoid(t):
    return 1/(1 + np.exp(-t))
def sigmoid_least_squares(w_0, w_1):
    cost = 0
    for i in range(y.size):
        cost += (sigmoid(w_0 + w_1* x[i])- y[i])**2
    return cost/y.size

In [84]:
w_0 = np.linspace(-20, 20, 90)
w_1 = np.linspace(-20, 20, 90)
w0, w1 = np.meshgrid(w_0, w_1)
cost = sigmoid_least_squares(w0, w1)

NameError: name 'sigmoid_least_squares' is not defined

In [173]:
from mpl_toolkits import mplot3d
import pylab as p
import mpl_toolkits.mplot3d.axes3d as p3
%matplotlib widget
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt


In [174]:
fig = plt.figure()
ax = p3.Axes3D(fig)


ax.plot_surface(w0,w1,cost, cmap='binary')
#     ax.contourf3D(w0,w1,cost)
ax.set_xlabel('w_0')
ax.set_ylabel('w_1')
ax.set_zlabel('cost');

ax.view_init(30, 121)
fig.add_axes(ax)
p.show()

FigureCanvasNbAgg()

/Users/lin_deng/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py:98: MatplotlibDeprecationWarning: 
Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  "Adding an axes using the same arguments as a previous axes "


In [29]:
# fig = plt.figure()
# ax = p3.Axes3D(fig)

# for i in range(20, 180, 2):
#     ax.plot_surface(w0,w1,cost, cmap='binary')
#     # ax.contourf3D(w0,w1,cost)
#     ax.set_xlabel('w_0')
#     ax.set_ylabel('w_1')
#     ax.set_zlabel('cost');

#     ax.view_init(30, i)
#     fig.add_axes(ax)
#     filename='GIF/step'+str(i)+'.png'
#     plt.savefig(filename, dpi=96)
# #     p.show()

FigureCanvasNbAgg()

/Users/lin_deng/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py:98: MatplotlibDeprecationWarning: 
Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  "Adding an axes using the same arguments as a previous axes "


In [35]:
from IPython.display import IFrame
IFrame('GIF/LS_gif.gif', width=600, height=500)

### Least Squares

In [35]:
def sigmoid(t):
    return 1/(1 + np.exp(-t))

def gradient(t, y):
    outcome = (sigmoid(t)**2 - sigmoid(t)**3 - y*sigmoid(t) + y*sigmoid(t)**2)*t
    return 2 * outcome

In [36]:
alpha = 0.0001
g = 0
w = np.array([-20, 20])
iteration = 0
for t in range(5000):
    for i in range(x.size):
        grad = gradient((np.dot(w.T, X[i])), y[i])
        g += grad
#         print("gradient = {} | g = {}".format(grad, g))
#     if abs(grad) <= 0.001:
#         break
        
    w = w - alpha * g
#     print("iter = {0} | w = {1} | gradient = {2}".format(iteration, w, grad))
    iteration += 1
    
print("iter = {0} | w = {1} | gradient = {2}".format(iteration, w, grad))
   

iter = 5000 | w = [-19.83051035  20.16948965] | gradient = 0.0


In [37]:
output_file("logit_03.html")
p4 = figure(plot_height = 300, plot_width = 300,
            tools = "", title = "Mean Squared Error Cost")
p4.circle(x = x, y = y)
p4.toolbar.logo = None
p4.add_layout(hline)
y2 = sigmoid(np.dot(w.T, X.T))
y3 = np.where(y2 > 0.5, 1, 0)
p4.line(x = x, y = y2.flatten(), color = "red")
show(row(p3, p4))

## Cross Entropy (Penalty) Cost Function

In [44]:
input_x = np.linspace(0.001, 1, 100)
output_y = -np.log(sigmoid(input_x))
output_y1 = -np.log(1 - sigmoid(input_x))

In [45]:
output_file("logit_04.html")
fig0 = figure(plot_height = 200, plot_width = 300,
            tools = "", title = "y = 1")
fig0.yaxis.visible = False
fig0.toolbar.logo = None
fig0.line(x = input_x, y = output_y, color = 'black')

fig1 = figure(plot_height = 200, plot_width = 300,
           tools = "", title = "y = 0")
fig1.yaxis.visible = False
fig1.toolbar.logo = None
fig1.line(x = input_x, y = output_y1, color = 'black')
fig0.yaxis.axis_label = 'cost'
fig0.xaxis.axis_label = 'sigmoid'
fig1.yaxis.axis_label = 'cost'
fig1.xaxis.axis_label = 'sigmoid'
show(row(fig0, fig1))

## Using Gradient Descent find optimal parameters

In [38]:
def gradFunc(w, X, y, N):
    grad = 0
    for i in range(N):
        grad += (y[i] - sigmoid(np.dot(w.T, X[i]))) * X[i]
    return (-1/N) * grad

# Initialization
alpha = 5
w = np.array([20.0, 20.0])
N = y.size
iteration = 0
w_collect = [w]
for i in range(5000):
    gradient = gradFunc(w, X, y, N)
    w -= alpha * gradient
    w_collect.append(w)
#     if abs(sum(w_collect[-1] - w_collect[-2])) < 0.00001:
#         break
    
#     print("iter = {0} | w = {1} | gradient = {2}".format(iteration, w, grad))
    iteration += 1

w

array([-36.43976765,  34.95182241])

In [39]:
output_file("logit_04.html")
p5 = figure(plot_height = 300, plot_width = 300,
            tools = "", title = "Gradient Descent")
p5.circle(x = x, y = y)
p5.toolbar.logo = None
p5.add_layout(hline)
y2 = sigmoid(np.dot(w.T, X.T))
# y3 = np.where(y2 > 0.5, 1, 0)
p5.line(x = x, y = y2.flatten(), color = "red")
show(row(p3, p5))

## Using Newton's Method

In [64]:
def newton(N, X, w):
    secGrad = 0
    for i in range(N):
        secGrad += (sigmoid(np.dot(w.T, X[i])) * (1 - sigmoid(np.dot(w.T, X[i]))) * 
                        np.dot(X[i].T, X[i]))
    return 1/N * secGrad

# Initialization
w = np.array([-20.0, 20.0])
N = y.size
iteration = 0
w_collect = [w]
for i in range(5000):
    w = w - gradFunc(w, X, y, N)/newton(N, X, w)
    
    w_collect.append(w)
#     if abs(sum(w_collect[-1] - w_collect[-2])) < 0.00001:
#         break
    
#     print("iter = {0} | w = {1} | gradient = {2}".format(iteration, w, grad))
    iteration += 1
w

array([-93.16567685,  89.30983868])

In [74]:
w_collect[-10:]

[array([-93.04326026,  89.19252547]),
 array([-93.05686236,  89.20556052]),
 array([-93.0704644,  89.2185955]),
 array([-93.08406637,  89.23163043]),
 array([-93.09766828,  89.24466529]),
 array([-93.11127012,  89.25770009]),
 array([-93.1248719 ,  89.27073483]),
 array([-93.13847361,  89.28376951]),
 array([-93.15207526,  89.29680412]),
 array([-93.16567685,  89.30983868])]

In [28]:
reset_output()

In [43]:
output_file("logit_05.html")
p6 = figure(plot_height = 300, plot_width = 300,
            tools = "", title = "Newton's Method")
p6.circle(x = x, y = y)
p6.toolbar.logo = None
p6.add_layout(hline)
y2 = sigmoid(np.dot(w.T, X.T))
# y3 = np.where(y2 > 0.5, 1, 0)
p6.line(x = x, y = y2.flatten(), color = "red")
p6.toolbar.logo = None
# grid = gridplot([[p2,None], [p3, p4], [p5, p6]], toolbar_options=dict(logo=None))
show(row(p5, p6))